### ISSUE TITLE
Text selection is invisible.

### ISSUE THREAD

**Issue by david-von-tamar** [AdaCore/gnatstudio#79]
I can't see the selection background (typically light blue in other editors) when selecting text in the editor. Although the foreground changes to default, the background remains white and I can't see what I'm selecting.

I've also tried to use default themes (both the default light color scheme for the editor, and the default Adwaita GTK theme on Debian) on a fresh GPS install, but I still can't see my selection.

My version is **GNAT 8.3.0** and **GPS 2018**.
I'm running it on Debian 10.

**Comment by ogorodnik** [comment]
Hello,
We have never heard about such problem so I guess it is kind of some local problems on your side.
For beginning I would suggest to remove old gpr, old @user_home@/.gps directory and after that install gps again.

If it does not help, you can test whether gps log file contains something unexpected and inform us about this. 

Best regards.

**Comment by atupone** [comment]
I suppose is the same problem that affects https://github.com/AdaCore/gps/issues/53

**Comment by david-tamar** [comment]
> Hello,
> We have never heard about such problem so I guess it is kind of some local problems on your side.
> For beginning I would suggest to remove old gpr, old @user_home@/.gps directory and after that install gps again.
> 
> If it does not help, you can test whether gps log file contains something unexpected and inform us about this.
> 
> Best regards.

I'm on Debian Sid now, and the problem still persists after several months.
I have a fresh install of GNAT and GPS 18 without any user configs. I use the default bright theme, and GTK's default Adwaita theme for the rest of the UI. 

Here's a screenshot if you don't believe me, this is how the text looks like without selection:
![image](https://user-images.githubusercontent.com/24723374/66709041-6a73d780-ed64-11e9-93ce-728df7aed68a.png)

And this is after the selection (the text becomes black, but the background is just white):
![image](https://user-images.githubusercontent.com/24723374/66709044-824b5b80-ed64-11e9-9b37-bc180da368dc.png)

Every time I want to learn Ada, these UI bugs in the IDE instantly repel me away from this language because I won't use other bloated IDEs like VSCode, IntelliJ or Emacs to write Ada one day.

Other bugs related to the editor:

1. The context menu (right mouse click) in the editor shows in monospaced font, but it should show in regular sans-serif font as the rest of the GUI.
2. When selecting text in the editor, non of the menu-items that have to do with selection in Edit become available, they just stay grayed out as if I selected nothing.
3. Some foreground colors in GPS's UI are not consistent with the rest of the system's colors. It's as if their color was hard-coded by GPS, instead of just letting GTK do its job by applying the theme's stylesheet consistently on the user interface.

**Comment by AnthonyLeonardoGracio** [comment]
Hi @david-tamar ,

I remember that you are using a completeley empty gps.css, right?

Here is a screenshot of what I get with the development version of GPS without anything in gps.css (on Ubuntu 16.04).

<img width="1284" alt="Capture d’écran 2019-10-29 à 15 53 08" src="https://user-images.githubusercontent.com/5286422/67779070-6df5a700-fa64-11e9-96f2-87d9fbf9763f.png">

I don't encounter the issues that your mention. It's ugly, but I can see the selected text and my contextual menus don't use a monospace font.

We may have fixed the issues that you encounter since then. Or it may be an issue specific to your setup.

Regards,

**Comment by atupone** [comment]
I have fixed this problem on gentoo.
We had a too new gtk+-3 version in the tree.
gps uses 3.18 and we had 3.24. 
3.24 is to new for GPS-2018.
So we installed a version of gtk+-3.18 only for usage in gps.
See if you can install gtk+-3.18 on debian (I don't know how)

**Comment by david-tamar** [comment]
@AnthonyLeonardoGracio, 

The screenshots I posted were before I tried using GPS with an empty `gps.css`, as my OP states: *all defaults out of the box* both Debian and GPS. Emptying `gps.css` did not fix this particular bug, which is the reason I don't use GPS at all.

The user interface with an empty `gps.css` looks much better, because AdaCore's stylesheet breaks the standard GTK theme (*Adwaita*) by showing unreadable foreground colors against nearly the same background colors (for example: white against light-gray, or light-gray against white, etc...) with all default settings under GTK's own official theme (which is *Adwaita*, I repeat that a lot, because some people don't know that *Adwaita* is how Linux usually looks like). On top of that, different GTK themes that are perfectly legal and adhere to GTK's CSS styling protocol completely break AdaCore's own stylesheet for obvious reasons, even GTK's own *Adwaita Dark* variant breaks `gps.css`. Either way, the stylesheet itself is not the reason why text selections are invisible on standard GTK environments, as I previously stated, it's because of some weird bug at GtkAda that also breaks line number for some reason. 

You seem to be using an OS that ships with a non-standard GTK environment. According to your screenshots, I'm assuming that you are using Ubuntu, which is different from standard Linux environments at large (especially the GTK/Gnome part) in the sense that Canonical is inflicting its own corporate marketing/branding/policies/patching on standard software, this may break portability, and they do cause a lot of damage and fragmentation to *nix in that regard, because most people think that Ubuntu is representative of Linux, whereas it's a misrepresentation of Linux because it doesn't stick to the original software as released by the developers. This includes Gnome and GTK at large. Following that logic, Ubuntu (or any other distribution that alters/patches software like graphical toolkits (GTK/Qt) or DEs (like Gnome/Xfce) in general) should never be used for reproduction of UI bugs in any software, because results on Ubuntu do not reflect on how your software works normally out of the box on the software that you rely (GTK).

After desperate attempts to reconfigure GPS and GTK several times, I gave up on GPS altogether about two weeks ago. I no longer plan to use GPS for future development with Ada because it's simply unusable although I wish it was. It's unstable, and has serious UI bugs on Debian - which is arguably the most stable, mature, established, organized, and disciplined Linux distribution out there. Despite of Debian's culture, I still kept experiencing these bugs with 4 different releases of Debian, firstly on _Stretch_ (old-stable/9), then _Buster_ (stable/10, that's when I started to report some of these bugs), then on _Bullseye_ (testing/11), and now on _Sid_ (unstable/rolling).

**Comment by AnthonyLeonardoGracio** [comment]
First, did you build GPS yourself or did you use the community version?

Because, as @atupone, GPS should be used with Gtk 3.14+. Note that the community version of GPS comes with this version of the Gtk library, so everything should work out-of-the-box.

If you build GPS yourself that's a completely different story of course. We also set a number of Gtk- related variables in a wrapper (which is the script that gets executed when typing 'gps' after installing it): if you don't launch GPS with it you may have some problems.

**Comment by Norberto-CdP** [comment]
> @AnthonyLeonardoGracio,
> 
> The screenshots I posted were before I tried using GPS with an empty `gps.css`, as my OP states: _all defaults out of the box_ both Debian and GPS. Emptying `gps.css` did not fix this particular bug, which is the reason I don't use GPS at all.
> 
> The user interface with an empty `gps.css` looks much better, because AdaCore's stylesheet breaks the standard GTK theme (_Adwaita_) by showing unreadable foreground colors against nearly the same background colors (for example: white against light-gray, or light-gray against white, etc...) with all default settings under GTK's own official theme (which is _Adwaita_, I repeat that a lot, because some people don't know that _Adwaita_ is how Linux usually looks like). On top of that, different GTK themes that are perfectly legal and adhere to GTK's CSS styling protocol completely break AdaCore's own stylesheet for obvious reasons, even GTK's own _Adwaita Dark_ variant breaks `gps.css`. Either way, the stylesheet itself is not the reason why text selections are invisible on standard GTK environments, as I previously stated, it's because of some weird bug at GtkAda that also breaks line number for some reason.
> 
> You seem to be using an OS that ships with a non-standard GTK environment. According to your screenshots, I'm assuming that you are using Ubuntu, which is different from standard Linux environments at large (especially the GTK/Gnome part) in the sense that Canonical is inflicting its own corporate marketing/branding/policies/patching on standard software, this may break portability, and they do cause a lot of damage and fragmentation to *nix in that regard, because most people think that Ubuntu is representative of Linux, whereas it's a misrepresentation of Linux because it doesn't stick to the original software as released by the developers. This includes Gnome and GTK at large. Following that logic, Ubuntu (or any other distribution that alters/patches software like graphical toolkits (GTK/Qt) or DEs (like Gnome/Xfce) in general) should never be used for reproduction of UI bugs in any software, because results on Ubuntu do not reflect on how your software works normally out of the box on the software that you rely (GTK).
> 
> After desperate attempts to reconfigure GPS and GTK several times, I gave up on GPS altogether about two weeks ago. I no longer plan to use GPS for future development with Ada because it's simply unusable although I wish it was. It's unstable, and has serious UI bugs on Debian - which is arguably the most stable, mature, established, organized, and disciplined Linux distribution out there. Despite of Debian's culture, I still kept experiencing these bugs with 4 different releases of Debian, firstly on _Stretch_ (old-stable/9), then _Buster_ (stable/10, that's when I started to report some of these bugs), then on _Bullseye_ (testing/11), and now on _Sid_ (unstable/rolling).

I totally agree with you. I had the same problem and after trying a lot of alternatives, I found the following solution.

GPS -> Edit -> Preferences -> Editor -> Fonts & Colors -> General -> Default (Select background color as null -gray squares-).

It works for me on debian 10 (KDE Plasma) with a dark custom color choice on the desktop and with the Darkside option on the GPS Color Theme.

Hope it works for you.

**Comment by AnthonyLeonardoGracio** [comment]
> > @AnthonyLeonardoGracio,
> > The screenshots I posted were before I tried using GPS with an empty `gps.css`, as my OP states: _all defaults out of the box_ both Debian and GPS. Emptying `gps.css` did not fix this particular bug, which is the reason I don't use GPS at all.
> > The user interface with an empty `gps.css` looks much better, because AdaCore's stylesheet breaks the standard GTK theme (_Adwaita_) by showing unreadable foreground colors against nearly the same background colors (for example: white against light-gray, or light-gray against white, etc...) with all default settings under GTK's own official theme (which is _Adwaita_, I repeat that a lot, because some people don't know that _Adwaita_ is how Linux usually looks like). On top of that, different GTK themes that are perfectly legal and adhere to GTK's CSS styling protocol completely break AdaCore's own stylesheet for obvious reasons, even GTK's own _Adwaita Dark_ variant breaks `gps.css`. Either way, the stylesheet itself is not the reason why text selections are invisible on standard GTK environments, as I previously stated, it's because of some weird bug at GtkAda that also breaks line number for some reason.
> > You seem to be using an OS that ships with a non-standard GTK environment. According to your screenshots, I'm assuming that you are using Ubuntu, which is different from standard Linux environments at large (especially the GTK/Gnome part) in the sense that Canonical is inflicting its own corporate marketing/branding/policies/patching on standard software, this may break portability, and they do cause a lot of damage and fragmentation to *nix in that regard, because most people think that Ubuntu is representative of Linux, whereas it's a misrepresentation of Linux because it doesn't stick to the original software as released by the developers. This includes Gnome and GTK at large. Following that logic, Ubuntu (or any other distribution that alters/patches software like graphical toolkits (GTK/Qt) or DEs (like Gnome/Xfce) in general) should never be used for reproduction of UI bugs in any software, because results on Ubuntu do not reflect on how your software works normally out of the box on the software that you rely (GTK).
> > After desperate attempts to reconfigure GPS and GTK several times, I gave up on GPS altogether about two weeks ago. I no longer plan to use GPS for future development with Ada because it's simply unusable although I wish it was. It's unstable, and has serious UI bugs on Debian - which is arguably the most stable, mature, established, organized, and disciplined Linux distribution out there. Despite of Debian's culture, I still kept experiencing these bugs with 4 different releases of Debian, firstly on _Stretch_ (old-stable/9), then _Buster_ (stable/10, that's when I started to report some of these bugs), then on _Bullseye_ (testing/11), and now on _Sid_ (unstable/rolling).
> 
> I totally agree with you. I had the same problem and after trying a lot of alternatives, I found the following solution.
> 
> GPS -> Edit -> Preferences -> Editor -> Fonts & Colors -> General -> Default (Select background color as null -gray squares-).
> 
> It works for me on debian 10 (KDE Plasma) with a dark custom color choice on the desktop and with the Darkside option on the GPS Color Theme.
> 
> Hope it works for you.

Did it happen with the Community version or with a custom build?

**Comment by Norberto-CdP** [comment]
@AnthonyLeonardoGracio 

I've installed the debian gnat-gps package, so I guess I'm using community version.

**Comment by AnthonyLeonardoGracio** [comment]
> @AnthonyLeonardoGracio
> 
> I've installed the debian gnat-gps package, so I guess I'm using community version.

No, these packages are not maintained by AdaCore actually. To download the Community version just go on AdaCore's website:  https://www.adacore.com/download

Note that we will release a new Community version soon, probably at the beginning of May, so don't hesitate to try it out since this issue may have been fixed since then.

**Comment by Norberto-CdP** [comment]
Thank you very much for your help.

**Comment by AnthonyLeonardoGracio** [comment]
You are welcome!

**Comment by kevlar700** [comment]
> GPS -> Edit -> Preferences -> Editor -> Fonts & Colors -> General -> Default (Select background color as null -gray squares-).
> 
> It works for me on debian 10 (KDE Plasma) with a dark custom color choice on the desktop and with the Darkside option on the GPS Color Theme.
> 
> Hope it works for you.

That works for me. I guess libgtk-3.24 is too new. It does make the non editor window backgrounds rather dark and ugly though.

I'm happy using a heavy editor actually but I find help->Gnat Runtime helpful.

I assume that functionality is not available in other IDEs?

WRT community edition, it's license prohibits use by companies, does it not!

**Comment by kevlar700** [comment]
Line numbers also end at the first procedure, even after deleting the .gps folder.

**Comment by kevlar700** [comment]
AFAICT the only distro to have working gnat-gps is Gentoo right now, which requires a time investment. I believe that even Debian stable has backported libgtk-3.24.

Can the CE edition become an optional support edition. The free ada development environment, isn't very welcoming right now including vscode as gnat-gps provides links to the reference material!

Alternatively a snap, or flatpak or alire might bundle the older libs?
